### PR TITLE
Use only one backend

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Review by AlexBerkovich — APPROVED** [review]
Looks good to me! 
Happy to start testing it.
Luke - your thoughts?

**Comment by luke841** [comment]
i'm happy with the code. Just need to figure out how to test and hot swap in the code

**Comment by luke841** [comment]
@jayvdb Trying to run with act but get the following error.
[triton_act_logs.log](https://github.com/luke841/triton/files/8657086/triton_act_logs.log)

**Comment by jayvdb** [comment]
The CI works - see https://github.com/jayvdb/triton-1/actions/runs/2292749441

**Review by luke841 — APPROVED** [review]

**Pull request merged**
